language: java
sudo: required
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7
branches:
  only:
    - 1.0.15
services:
  - redis-server
before_install:
  - wget https://github.com/antirez/redis/archive/3.2.3.tar.gz && tar -xvzf 3.2.3.tar.gz && cd redis-3.2.3 && make && cd src && nohup ./redis-server --port 6380 --requirepass test &
before_script:
  - sleep 10
script: "mvn clean package -P travis"
after_success:
  - mvn clean test jacoco:report coveralls:report