language: java
sudo: required
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7
branches:
  only:
    - master
services:
  - redis-server
script: "mvn clean package -P travis -Dmaven.test.skip=true"
