language: java
sudo: required
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7
branches:
  only:
    - master
services:
  - redis-server
before_script:
  - sleep 10
script: "mvn clean package -P travis"
